from src.utils.paths import SRC_DIR

YOLO_CONFIG_FILE = SRC_DIR.joinpath("detection/yolov3/cfg/yolov3-tiny.cfg")
TRAIN_YOLO_IOU_IGNORE_THRES = .7
TRAIN_YOLO_CONF_THRESHOLD = .5
TEST_YOLO_CONF_THRESHOLD = .7
RESIZE_MODE_CROP = 'crop'
RESIZE_MODE_PAD = 'pad'
RESIZE_MODE = RESIZE_MODE_CROP

JGRJ2O_TRAIN_BATCH_SIZE = 64
JGRJ2O_TEST_BATCH_SIZE = 1
JGRJ2O_LEARNING_RATE = 0.0000117
JGRJ2O_LR_DECAY = 0.93
JGRJ2O_WEIGHT_DECAY = 0.00005

OTSUS_ALLOWANCE_THRESHOLD = 0.01

